version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - SECRET_KEY=your-secret-key-here
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY:-}
      - MODERATION_ENABLED=true
      - DEFAULT_AUTO_REPLY_DELAY=60
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery-worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - SECRET_KEY=your-secret-key-here
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY:-}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
      - api

  celery-beat:
    build: .
    command: celery -A app.celery beat --loglevel=info
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - SECRET_KEY=your-secret-key-here
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY:-}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
      - api

volumes:
  redis_data: 